Public class BAGAHNSOL_ACTIVITY_VI {
    public static void main(String{}args){
         Scanner sc = new Scanner(System.in);
    System.out.println (x:"enter the firts number":);
     int num=sc.nextline();
    System.out.println(x:"enter the second number");
    int num2=sc.nextline();

    int sum=num1 = num2;
    int deff=num1 -num2;
    int pod=num1 * num2;

    System.out.println(sum);
    System.out.println(diff);
    System.out,println(pod);
    }
   
    
}
 
  
       
       

